/* Shadow Ascension · Phaser Apex HUD v0.1 */
(function(){
'use strict';
let root=null,last='';
const get=n=>{try{return globalThis.eval(n)}catch(_){return null}};
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:[];
function boot(){if(root)return;root=document.createElement('div');root.id='phaser-apex-hud';root.style.cssText='position:fixed;inset:0;z-index:20;pointer-events:none;font-family:Inter,system-ui,sans-serif;color:#f3efff;text-shadow:0 2px 4px #000;';root.innerHTML=`<div id="apex-vitals" style="position:absolute;left:22px;bottom:22px;width:min(330px,42vw)"><div style="display:flex;justify-content:space-between;font-size:12px;letter-spacing:.12em;margin-bottom:5px"><b id="apex-name">ОХОТНИК</b><span id="apex-level">LV 1</span></div><div style="height:13px;background:#120d1b;border:1px solid #4a3b61;border-radius:7px;overflow:hidden;box-shadow:0 0 18px #000"><i id="apex-hp" style="display:block;height:100%;width:100%;background:linear-gradient(90deg,#a72e52,#e85d75);transition:width .12s"></i></div><div style="height:7px;margin-top:4px;background:#120d1b;border:1px solid #3d3554;border-radius:5px;overflow:hidden"><i id="apex-mp" style="display:block;height:100%;width:100%;background:#6354b5;transition:width .12s"></i></div><div id="apex-stats" style="font-size:10px;opacity:.72;margin-top:6px"></div></div><div id="apex-target" style="position:absolute;right:22px;top:22px;width:min(300px,34vw);display:none"><div style="font-size:12px;letter-spacing:.12em;display:flex;justify-content:space-between"><b id="apex-target-name">ТЕНЬ</b><span id="apex-target-rank"></span></div><div style="height:9px;background:#120d1b;border:1px solid #4a3b61;border-radius:5px;overflow:hidden;margin-top:5px"><i id="apex-target-hp" style="display:block;height:100%;width:100%;background:#d95870"></i></div></div><div id="apex-zone" style="position:absolute;left:50%;top:18px;transform:translateX(-50%);text-align:center;letter-spacing:.18em;font-size:10px;opacity:.7"></div>`;document.body.appendChild(root)}
function tick(){boot();const G=get('G'),p=G&&G.player;if(!G||!p)return;const hp=n(p.hp),mx=Math.max(1,n(p.maxhp,1)),mp=n(p.mp),mm=Math.max(1,n(p.maxmp,1));const vals={name:p.name||'ОХОТНИК',level:p.level||1,hp:Math.round(hp),mx:Math.round(mx),mp:Math.round(mp),mm:Math.round(mm),enemies:arr(G.enemies).length,gold:Math.round(n(p.gold)),crystals:Math.round(n(p.crystals)),fury:Math.round(n(p.fury))};const key=JSON.stringify(vals);if(key===last)return;last=key;
 const q=id=>document.getElementById(id);q('apex-name').textContent=vals.name;q('apex-level').textContent='LV '+vals.level;q('apex-hp').style.width=Math.max(0,Math.min(100,hp/mx*100))+'%';q('apex-mp').style.width=Math.max(0,Math.min(100,mp/mm*100))+'%';q('apex-stats').textContent=`HP ${vals.hp}/${vals.mx} · MP ${vals.mp}/${vals.mm} · ⚔ ${vals.enemies} · ✦ ${vals.gold} · ◇ ${vals.crystals}`;
 const es=arr(G.enemies).filter(e=>e&&Number.isFinite(Number(e.x))&&Number.isFinite(Number(e.y)));const target=es.sort((a,b)=>((a.hp??a.health??0)-(b.hp??b.health??0)))[0];const box=q('apex-target');if(target){box.style.display='block';q('apex-target-name').textContent=String(target.name||target.type||target.kind||'ТЕНЬ').toUpperCase();q('apex-target-rank').textContent=target.boss?'BOSS':target.elite?'ELITE':'';const eh=n(target.hp??target.health),em=Math.max(1,n(target.maxhp??target.maxHP??target.healthMax,eh||1));q('apex-target-hp').style.width=Math.max(0,Math.min(100,eh/em*100))+'%'}else box.style.display='none';q('apex-zone').textContent=G.mode==='hub'?'МИР · ТОЧКА СБОРА':G.mode==='gate'?'ВРАТА · ОХОТА':'DUNGEON';}
window.addEventListener('load',()=>setInterval(tick,120));window.addEventListener('shadow-start-phaser',boot);globalThis.__shadowPhaserApexHUD={version:'0.1.0',boot};
})();
